name: tadeumendonca.io
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'terraform/**'
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
      - 'terraform/**'
      - 'src/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3
          cli_config_credentials_token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
      
      - name: Terraform fmt
        id: fmt
        working-directory: terraform
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform int
        id: init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform validate
        id: validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform plan
        id: plan
        working-directory: terraform
        run: |
          terraform plan -out=tfplan.out -detailed-exitcode -var-file=./env/main.tfvars || exit_code=$?
          if [ "${exit_code:-0}" -eq 0 ]; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          elif [ "$exit_code" -eq 2 ]; then
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "Terraform plan failed"
            exit 1
          fi
        
      - name: Terraform apply
        if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' && steps.plan.outputs.no_changes == 'false') || github.event_name == 'push' }}
        working-directory: terraform
        run: terraform apply -auto-approve tfplan.out
        
      - name: Terraform destroy
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy' }}
        working-directory: terraform
        run: terraform destroy -auto-approve -var-file=./env/main.tfvars